In [1]:
import pandas as pd
import requests
import json

In [2]:
villes_coordonees = pd.DataFrame({
    'destination': ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]
})

villes_coordonees['lon'] =0
villes_coordonees['lat'] =0

In [3]:
url = "https://nominatim.openstreetmap.org/search"

params = {
    'q': 'Paris, France',
    'format': 'json',
    'addressdetails': 1,
    'limit': 1
}

headers = {
    'User-Agent': 'maurice.had@gmail.com'
}
response = requests.get(url, params=params, headers=headers)
ville_unique = response.json()
ville_unique

[{'place_id': 88664949,
  'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
  'osm_type': 'relation',
  'osm_id': 71525,
  'lat': '48.8534951',
  'lon': '2.3483915',
  'class': 'boundary',
  'type': 'administrative',
  'place_rank': 12,
  'importance': 0.8845663630228834,
  'addresstype': 'city',
  'name': 'Paris',
  'display_name': 'Paris, Île-de-France, France métropolitaine, France',
  'address': {'city': 'Paris',
   'ISO3166-2-lvl6': 'FR-75C',
   'state': 'Île-de-France',
   'ISO3166-2-lvl4': 'FR-IDF',
   'region': 'France métropolitaine',
   'country': 'France',
   'country_code': 'fr'},
  'boundingbox': ['48.8155755', '48.9021560', '2.2241220', '2.4697602']}]

In [4]:
villes_coordonees['lat'] = villes_coordonees['lat'].astype(float)
villes_coordonees['lon'] = villes_coordonees['lon'].astype(float)

lat = float(ville_unique[0]['lat'])
lon = float(ville_unique[0]['lon'])
            
villes_coordonees.at[5, 'lat'] = lat
villes_coordonees.at[5, 'lon'] = lon

villes_coordonees

                     destination       lon        lat
0              Mont Saint Michel  0.000000   0.000000
1                        St Malo  0.000000   0.000000
2                         Bayeux  0.000000   0.000000
3                       Le Havre  0.000000   0.000000
4                          Rouen  0.000000   0.000000
5                          Paris  2.348391  48.853495
6                         Amiens  0.000000   0.000000
7                          Lille  0.000000   0.000000
8                     Strasbourg  0.000000   0.000000
9   Chateau du Haut Koenigsbourg  0.000000   0.000000
10                        Colmar  0.000000   0.000000
11                     Eguisheim  0.000000   0.000000
12                      Besancon  0.000000   0.000000
13                         Dijon  0.000000   0.000000
14                        Annecy  0.000000   0.000000
15                      Grenoble  0.000000   0.000000
16                          Lyon  0.000000   0.000000
17              Gorges du Verdon  0.000000   0.000000
18            Bormes les Mimosas  0.000000   0.000000
19                        Cassis  0.000000   0.000000
20                     Marseille  0.000000   0.000000
21               Aix en Provence  0.000000   0.000000
22                       Avignon  0.000000   0.000000
23                          Uzes  0.000000   0.000000
24                         Nimes  0.000000   0.000000
25                 Aigues Mortes  0.000000   0.000000
26      Saintes Maries de la mer  0.000000   0.000000
27                     Collioure  0.000000   0.000000
28                   Carcassonne  0.000000   0.000000
29                        Ariege  0.000000   0.000000
30                      Toulouse  0.000000   0.000000
31                     Montauban  0.000000   0.000000
32                      Biarritz  0.000000   0.000000
33                       Bayonne  0.000000   0.000000
34                   La Rochelle  0.000000   0.000000

In [5]:
for index, row in villes_coordonees.iterrows():
    city = row['destination']
    
    params = {
        'q': city,
        'format': 'json',
        'addressdetails': 1
    }
    
    url = "https://nominatim.openstreetmap.org/search"
    headers = {'User-Agent': 'maurice.had@gmail.com'}  
    
    response = requests.get(url, params=params, headers=headers)
    if response.status_code == 200:
        ville_unique = response.json()
        
        lat = float(ville_unique[0]['lat'])
        lon = float(ville_unique[0]['lon'])
            
        villes_coordonees.at[index, 'lat'] = lat
        villes_coordonees.at[index, 'lon'] = lon
        
        print(f'{city} importée')
        
    else:
        print(f"Erreur pour la ville {city} : code {response.status_code}")
        
villes_coordonees

Mont Saint Michel importée
St Malo importée
Bayeux importée
Le Havre importée
Rouen importée
Paris importée
Amiens importée
Lille importée
Strasbourg importée
Chateau du Haut Koenigsbourg importée
Colmar importée
Eguisheim importée
Besancon importée
Dijon importée
Annecy importée
Grenoble importée
Lyon importée
Gorges du Verdon importée
Bormes les Mimosas importée
Cassis importée
Marseille importée
Aix en Provence importée
Avignon importée
Uzes importée
Nimes importée
Aigues Mortes importée
Saintes Maries de la mer importée
Collioure importée
Carcassonne importée
Ariege importée
Toulouse importée
Montauban importée
Biarritz importée
Bayonne importée
La Rochelle importée

                     destination       lon        lat
0              Mont Saint Michel -1.511460  48.635954
1                        St Malo -2.026041  48.649518
2                         Bayeux -0.702474  49.276462
3                       Le Havre  0.107973  49.493898
4                          Rouen  1.093966  49.440459
5                          Paris  2.348391  48.853495
6                         Amiens  2.295695  49.894171
7                          Lille  3.063528  50.636565
8                     Strasbourg  7.750713  48.584614
9   Chateau du Haut Koenigsbourg  7.344320  48.249411
10                        Colmar  7.357964  48.077752
11                     Eguisheim  7.307962  48.044797
12                      Besancon  6.024362  47.238022
13                         Dijon  5.041470  47.321581
14                        Annecy  6.128885  45.899235
15                      Grenoble  5.735782  45.187560
16                          Lyon  4.832011  45.757814
17              Gorges du Verdon  6.328562  43.749656
18            Bormes les Mimosas  6.341928  43.150697
19                        Cassis  5.539632  43.214036
20                     Marseille  5.369953  43.296174
21               Aix en Provence  5.447474  43.529842
22                       Avignon  4.805901  43.949249
23                          Uzes  4.419672  44.012128
24                         Nimes  4.360069  43.837425
25                 Aigues Mortes  4.191540  43.566152
26      Saintes Maries de la mer  4.427720  43.451592
27                     Collioure  3.083155  42.525050
28                   Carcassonne  2.349107  43.213036
29                        Ariege  1.406554  42.945537
30                      Toulouse  1.444247  43.604462
31                     Montauban  1.354999  44.017584
32                      Biarritz -1.552727  43.471144
33                       Bayonne -1.473666  43.494514
34                   La Rochelle -1.151595  46.159732

In [6]:
#classé par ordre alphabétique
villes_coordonees = villes_coordonees.sort_values(by='destination').reset_index(drop=True)
villes_coordonees

                     destination       lon        lat
0                  Aigues Mortes  4.191540  43.566152
1                Aix en Provence  5.447474  43.529842
2                         Amiens  2.295695  49.894171
3                         Annecy  6.128885  45.899235
4                         Ariege  1.406554  42.945537
5                        Avignon  4.805901  43.949249
6                         Bayeux -0.702474  49.276462
7                        Bayonne -1.473666  43.494514
8                       Besancon  6.024362  47.238022
9                       Biarritz -1.552727  43.471144
10            Bormes les Mimosas  6.341928  43.150697
11                   Carcassonne  2.349107  43.213036
12                        Cassis  5.539632  43.214036
13  Chateau du Haut Koenigsbourg  7.344320  48.249411
14                     Collioure  3.083155  42.525050
15                        Colmar  7.357964  48.077752
16                         Dijon  5.041470  47.321581
17                     Eguisheim  7.307962  48.044797
18              Gorges du Verdon  6.328562  43.749656
19                      Grenoble  5.735782  45.187560
20                   La Rochelle -1.151595  46.159732
21                      Le Havre  0.107973  49.493898
22                         Lille  3.063528  50.636565
23                          Lyon  4.832011  45.757814
24                     Marseille  5.369953  43.296174
25             Mont Saint Michel -1.511460  48.635954
26                     Montauban  1.354999  44.017584
27                         Nimes  4.360069  43.837425
28                         Paris  2.348391  48.853495
29                         Rouen  1.093966  49.440459
30      Saintes Maries de la mer  4.427720  43.451592
31                       St Malo -2.026041  48.649518
32                    Strasbourg  7.750713  48.584614
33                      Toulouse  1.444247  43.604462
34                          Uzes  4.419672  44.012128

In [7]:
#changer le nom de la colonne index : 

villes_coordonees = villes_coordonees.reset_index()
villes_coordonees.rename(columns={'index': 'id_destination'}, inplace=True)

villes_coordonees

    id_destination                   destination       lon        lat
0                0                 Aigues Mortes  4.191540  43.566152
1                1               Aix en Provence  5.447474  43.529842
2                2                        Amiens  2.295695  49.894171
3                3                        Annecy  6.128885  45.899235
4                4                        Ariege  1.406554  42.945537
5                5                       Avignon  4.805901  43.949249
6                6                        Bayeux -0.702474  49.276462
7                7                       Bayonne -1.473666  43.494514
8                8                      Besancon  6.024362  47.238022
9                9                      Biarritz -1.552727  43.471144
10              10            Bormes les Mimosas  6.341928  43.150697
11              11                   Carcassonne  2.349107  43.213036
12              12                        Cassis  5.539632  43.214036
13              13  Chateau du Haut Koenigsbourg  7.344320  48.249411
14              14                     Collioure  3.083155  42.525050
15              15                        Colmar  7.357964  48.077752
16              16                         Dijon  5.041470  47.321581
17              17                     Eguisheim  7.307962  48.044797
18              18              Gorges du Verdon  6.328562  43.749656
19              19                      Grenoble  5.735782  45.187560
20              20                   La Rochelle -1.151595  46.159732
21              21                      Le Havre  0.107973  49.493898
22              22                         Lille  3.063528  50.636565
23              23                          Lyon  4.832011  45.757814
24              24                     Marseille  5.369953  43.296174
25              25             Mont Saint Michel -1.511460  48.635954
26              26                     Montauban  1.354999  44.017584
27              27                         Nimes  4.360069  43.837425
28              28                         Paris  2.348391  48.853495
29              29                         Rouen  1.093966  49.440459
30              30      Saintes Maries de la mer  4.427720  43.451592
31              31                       St Malo -2.026041  48.649518
32              32                    Strasbourg  7.750713  48.584614
33              33                      Toulouse  1.444247  43.604462
34              34                          Uzes  4.419672  44.012128

In [8]:
#exporter en csv :

villes_coordonees.to_csv('./csv_files/villes_coordonnees.csv', index=False)